Add additional option that allows for the extension of the markdown parser
probablyup/markdown-to-jsx pull request #406
Opened 2021-10-27 08:27 UTC by lkuechler

This PR should allow for custom markdown syntax parsing as requested in this issue: https://github.com/probablyup/markdown-to-jsx/issues/313

I added a new property named `additionalParserRules` that can be given `MarkdownToJSX.Rules` which are added at the end of the already existing rules.

2021-11-02 19:55 UTC, jonotrybe commented
I am interested to see this PR merged. We are looking to use markdown-to-jsx for our needs but this would be needed

2021-11-10 15:35 UTC, probablyup commented on README.md
> +                    order: 2,
We should definitely encourage using the constants rather than their values

2021-11-10 15:36 UTC, probablyup commented
Generally fine with this PR, I previously had things private so I could refactor without a major version bump but that hasn't happened in a while so might as well allow the extension.

2021-11-10 16:14 UTC, lkuechler commented on README.md
> +                    order: 2,
Updated to use the `Priority` enum. For that I also have now exported this enum

2021-12-03 19:35 UTC, probablyup requested changes

2021-12-03 19:35 UTC, probablyup commented on README.md
> +                    order: Priority.MED,
need to add importing `Priority` to the example

2021-12-03 19:35 UTC, probablyup commented on README.md
> +                        return <u key={state.key}>{output(node.content, state)}</u>
One thing that occurred to me is markdown-to-jsx uses a custom JSX pragma to handle semantic element replacements and such. We would need to expose that `h(tag, props, children)` function to `react()` and the end result would look something more like this:

```js
react: (createElement, node, output, state) => {
  return createElement('u', {key: state.key}, output(node.content, state));
}
```

or perhaps

```js
react: (createElement, node, output, state) => {
  /* @jsx createElement */
  return <u key={state.key}>{output(node.content, state)}</u>
}
```

If jsx pragmas can be applied to particular block scopes.

2022-08-06 08:22 UTC, Innei commented
Hi, Is there any progress here？

2022-11-28 12:55 UTC, ernests commented
Any update on this?

2023-08-03 14:07 UTC, closed without merging

2023-08-04 08:09 UTC, huksley commented
@probablyup Have this been merged or implemented in a different way?